services:
  quiz-node:
    container_name: quiz-node
    image: node:20-alpine
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: >
      sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
