on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup caching
        uses: actions/setup-node@v4
        with:
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Build
        working-directory: ./frontend
        env:
          VITE_BASE_PATH: /quiz
        run: |
          npm install
          npm run test
          npm run build

      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: frontend/dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
